### ISSUE TITLE
npm install from github private packages failed

### ISSUE THREAD

**Issue by Jooyoung-dable** [npm/documentation#1037]
![스크린샷 2024-04-09 오후 2 15 49](https://github.com/npm/documentation/assets/61184548/6d89a52b-e6b2-4ee6-a6ce-4c6291d66eb4)

This morning, I encountered this error when installing a module in github private packages. Was there any issue?
No special action was taken, but it was resolved by afternoon.

**Comment by wraithgar** [comment]
This repo is for bugs with the npm docs site itself.  If you need support for the github package registry the link is here: https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages#contacting-support
