### ISSUE TITLE
Query about changing avatar in NPM account

### ISSUE THREAD

**Issue by km-saifullah** [npm/documentation#1070]
I create my NPM account. Now I want to change the avatar of my account. But I cannot do this even though I made a gravatar account. After click to the Change your Gravatar button it redirects me to the gravatar account but profile image did not change. What should I do right now?

**Comment by PAdventures** [comment]
> I create my NPM account. Now I want to change the avatar of my account. But I cannot do this even though I made a gravatar account. After click to the Change your Gravatar button it redirects me to the gravatar account but profile image did not change. What should I do right now?

Did you manage to solve this issue. I seem to be having the same problem as of right now

**Comment by km-saifullah** [comment]
@PAdventures  Just create an account in https://gravatar.com and then upload a photo there, it will change your profile photo. But it takes a while to change. So, be patient
