### ISSUE TITLE
"npm uninstall" do not remove all files

### ISSUE THREAD

**Issue by buhtz** [npm/documentation#1072]
Using "npm" from Debian stable. I am not familiar with npm and its universe.

I installed an application via

    $ npm i https://github.com/vweevers/hallmark

First problem is that this command did create a new folder (node_modules) and two files (package-lock.json and package.json) direct in my current working folder. This is behavior I do not expect from a package manager. From my users perspective this is a bug. I would expect to get the application installed into the system (like pip(x) does it in the Python universe).

Second problem is that even after installing the "hallmark" command is not available in my PATH. Don't know how to execute it. What is it what "npm" does when not installing it?

Third problem is that `$ npm uninstall hallmark` did not remove the three objects from the file system I mention in the first problem.

**Comment by wraithgar** [comment]
This repo is for issue with the documentation site of npm itself. For bugs in the cli use https://github.com/npm/cli/issues.
