### ISSUE TITLE
Include registry endpoints/API docs

### ISSUE THREAD

**Issue by Maniues** [npm/documentation#1113]
Since this repo is "Documentation for the npm registry...", maybe include documentation from https://github.com/npm/registry here?

**Comment by nnfhhvbb** [comment]
> 由於此儲存庫是“npm 註冊表的文件...”，因此可能包含來自https://github.com/npm/registry的文件？

**Comment by kenshanta** [comment]
By it's own definition, npm-registry is: A collection of **archived** documentation about registry endpoints/API.

Please close the issue as it is invalid
