### ISSUE TITLE
[BUG] Outdate links and tutorial

### ISSUE THREAD

**Issue by DavidMorenoDev** [npm/documentation#112]
# What / Why
The repository link to automatically update npm on windows is deprecated and read-only.

https://github.com/felixrieseberg/npm-windows-upgrade

The link for "edit your Windows installation's PATH" is from 10 years ago...I say that just to let you know

## When
https://docs.npmjs.com/try-the-latest-stable-version-of-npm

When I follow the tutorial to keep npm up to date on Windows

## Where

When I'm following the tutorial to keep npm up to date on Windows
### Current Behavior
The repository link to automatically update npm on windows is deprecated and read-only.

https://github.com/felixrieseberg/npm-windows-upgrade

The link for "edit your Windows installation's PATH" is from 10 years ago...I say that just to let you know

### Steps to Reproduce
Go to: https://docs.npmjs.com/try-the-latest-stable-version-of-npm and click on the links to keep Windows updated
### Expected Behavior

It should lead to updated material that can be used with Windows 10 to 11 and indicate what Windows is for

## Who
 n/a

## References
 n/a

**Comment by ArpitPal19** [comment]
@DavidMorenoDev  Hey I want to contribute  to this issues could you assign this to me and provide me preferable resources.

**Comment by MylesBorins** [comment]
Thanks for reporting @DavidMorenoDev, I've opened https://github.com/npm/documentation/pull/129 to remove the reference to the deprecated repostiory

@darcyclarke we should revisit the windows upgrade instructions.

@ArpitPal19 there isn't something specific that can be shared to help you pick this up... but if you want to review the overall "upgrade on windows" documentation and see if you can suggest improvements we would accept a contribution

**Comment by DavidMorenoDev** [comment]
> @DavidMorenoDev Hey I want to contribute to this issues could you assign this to me and provide me preferable resources.



> Thanks for reporting @DavidMorenoDev, I've opened #129 to remove the reference to the deprecated repostiory
> 
> @darcyclarke we should revisit the windows upgrade instructions.
> 
> @ArpitPal19 there isn't something specific that can be shared to help you pick this up... but if you want to review the overall "upgrade on windows" documentation and see if you can suggest improvements we would accept a contribution

Thank you @MylesBorins
