### ISSUE TITLE
Using cross-env for cross platform compatibility 

### ISSUE THREAD

**Issue by andrewnessinjim** [npm/documentation#1172]
I ran into this same issue: https://github.com/npm/documentation/issues/861 - the suggestion to use the set command for windows works fine. However, can we not use `cross-env` to make the npm commands work seamlessly across operating systems? I would like to make this change if that is a good idea. The changes would be in `package.json` file:
* A dependency on `cross-env` package.
* Prefixing `gatsby` and `develope:ssr` scripts with `cross-env` as they are the only two commands with environment variables.

If using `cross-env` is not a good idea, then perhaps we could mention in the `CONTRIBUTING.md`  guide to to use windows specific syntax where necessary.

**Comment by wraithgar** [comment]
`cross-env` is not being actively maintained.  I think a note in `CONTRIBUTING.md` is our best option for now.
