### ISSUE TITLE
"npm install" ignores "test" directory/"test" directories?

### ISSUE THREAD

**Issue by pwinkelm** [npm/documentation#1206]
When using npm 10.8.2 instead off 10.2.3 (changed to node 22.5.1 - node 21.2.0) it looks like an 'npm install' does not take over a "/dist/test" directory anymore.

In my package.json

    "own repo package": "git+https://secretkey@dev.azure.com/XXXorgXXX/XXXPATHXXX/_git/package#branche",

The repo has a /dist/test directory but it is not copied to the node_modules directory.

What is wrong?

**Comment by pwinkelm** [comment]
As a workaround I now renamed the "test" directory tot "tst". That worked.....

**Comment by wraithgar** [comment]
This doesn't seem like a documentation issue and there is not enough here to reproduce the issue.
