### ISSUE TITLE
"Install node with NVM" page doesn't tell you how to install node with NVM

### ISSUE THREAD

**Issue by zacharycohn** [npm/documentation#1214]
[This page](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) tells new users to install node using NVM. But it doesn't tell them *how* to install node via NVM.

Fix: Add some documentation, or a link to documentation, about how to install node via NVM.

**Comment by ljharb** [comment]
The link (the word "nvm") takes you to nvm's readme which tells you exactly how to do that. Is that insufficient?

**Comment by wraithgar** [comment]
The instructions for how to install nvm are best left on the nvm readme, where they can be updated as needed without npm having to try to keep mirror docs current.  And as stated already, the first metion of nvm is a link to the package with install instructions clearly outlined in the readme.
