### ISSUE TITLE
Vite 5 Pre-transform error - symlink directory behaviour  

### ISSUE THREAD

**Issue by melaich** [npm/documentation#1223]
When attempting to run a React.js + Vite app using pnpm, I encounter the following error in the browser console:
`Uncaught SyntaxError: missing ) after argument list (at main.tsx:6:51)`

Simultaneously, in the server console, the following message appears:
`[vite] Pre-transform error: Failed to load url /src/main.tsx (resolved id: C:/Users/myproject/src/main.tsx). Does the file exist?`

System Information:
    OS: Windows 10
    The project directory root from which I run the app is a symlink to another directory.

Question:
Is this behavior a regression in Vite 5 related to handling symlink paths, or could I be overlooking something?

**Comment by wraithgar** [comment]
This doesn't seem like it's related to the npm documentation.  You may have better luck asking Vite
