### ISSUE TITLE
I have `README.md` but in my npm package home page it's missing

### ISSUE THREAD

**Issue by SmallTeddy** [npm/documentation#1225]
[My Package Link](https://www.npmjs.com/package/vue-files-preview)

![image](https://github.com/user-attachments/assets/d6429138-4491-4c3e-baea-057be158ef1b)

![image](https://github.com/user-attachments/assets/9c499422-abf8-4ea3-95de-2a92a349e26c)

![image](https://github.com/user-attachments/assets/1b7d5d26-6d53-4f87-bc68-cff1dd92e8e2)

```[tasklist]
### Tasks
```

**Comment by wraithgar** [comment]
This is a website for the documentation site for npm.  If you have issues w/ the registry you should go through [support](https://www.npmjs.com/support).

It looks like [this incident was resolved](https://status.npmjs.org/incidents/qfmzhxz3frwb).
