### ISSUE TITLE
source code for  web page npmjs.com and dependents number inconsistency

### ISSUE THREAD

**Issue by Byron2016** [npm/documentation#1231]
Hi, I would like to know
1.  where can I find source code for  web page [npmjs.com](https://www.npmjs.com/)
2.  **Eslint** dependents number inconsistency 
 - in  [eslint](https://www.npmjs.com/package/eslint) it is possible to see that this package has `24347 dependants`

![image](https://github.com/user-attachments/assets/50af68a4-86a3-4b04-bbf6-cc91400a0df5)

 but if you browse in [packages depending on eslint](https://www.npmjs.com/browse/depended/eslint) it is only possible to **offset=360** [offset=360](https://www.npmjs.com/browse/depended/eslint?offset=360)  then if you calculate  there are only 395 dependents.

![image](https://github.com/user-attachments/assets/d5df822c-e906-467a-ad6d-d70f1837c0e2)

3. npm has a native way to obtaint **dependents** of a package using npm cli command?

**Comment by wraithgar** [comment]
No, there is not currently any way to programmatically discover all of the packages that depend on another given package.
