### ISSUE TITLE
Expand set of valid characters for a package name to include dot

### ISSUE THREAD

**Issue by Delapouite** [npm/documentation#1295]
Hi

From https://docs.npmjs.com/creating-a-package-json-file the current text states: 

> The "name" field contains your package's name, and must be lowercase and one word, and may contain hyphens and underscores.

It appears that dots can also be used, here's an example of package name with a dot: `gssapi.js` https://www.npmjs.com/package/gssapi.js

I think this should also be mentioned in the doc.

Thanks.

**Comment by kenshanta** [comment]
@Delapouite hope you don't mind me creating a PR for this minor fix

**Comment by kenshanta** [comment]
@Delapouite all set to close this issue

**Comment by wraithgar** [comment]
Fixed in https://github.com/npm/documentation/pull/1326
