### ISSUE TITLE
cafile vs certfile in .npmrc

### ISSUE THREAD

**Issue by Exotelis** [npm/documentation#1337]
In the [npm documentation](https://docs.npmjs.com/cli/v10/configuring-npm/npmrc#auth-related-configuration), it is stated that the `certfile` option can be used to specify the path to a certificate file. Interestingly, I kept encountering the following error:

 WARN  GET <private_registry> error (UNABLE_TO_VERIFY_LEAF_SIGNATURE). Will retry in 10 seconds. 2 retries left.

After spending some time troubleshooting, I tried using cafile instead (just out of curiosity), and it worked 😮

My user .npmrc now looks like this:

```
@some-scope:registry=<private_registry>
//<private_registry>/:cafile=${HOME}/.certificates/mycert.pem
```

So, is the documentation incorrect, or could this be a bug?

Versions i used: 
```
> npm -v
10.8.3
> node -v
v20.15.0
```

Edit: Issue id #1337 time to party 🥳🥳

**Comment by wraithgar** [comment]
Yeah that should be `cafile`.  It's in some config definition warnings too.

Fix: https://github.com/npm/cli/pull/7947
