### ISSUE TITLE
Example of creating node modules using Typescript

### ISSUE THREAD

**Issue by velara3** [npm/documentation#1340]
On this [page](https://docs.npmjs.com/creating-node-js-modules) there is an example that shows exporting a single JavaScript function. I've created a module that has Typescript in it and I've been told I'm doing it wrong. But if I don't create it the way I do it doesn't work. 

Could someone create an example of an npm module that uses Typescript? An example project or example instructions?

**Comment by wraithgar** [comment]
This is more of a task for the typescript documentation, not npm.  The npm docs are meant to be very basic, not comprehensive.
