### ISSUE TITLE
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.[BUG] <title>

### ISSUE THREAD

**Issue by kamarjahan1234** [npm/documentation#135]
# What / Why

 -->
> n/a

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by alasdairhurst** [comment]
Is it just me or is this actually missing from the docs?

**Comment by ljharb** [comment]
Nothing is deprecated; that message was a bug.
