### ISSUE TITLE
Documentation for `npm ls` still references future changes that might be coming with V8

### ISSUE THREAD

**Issue by martinblume** [npm/documentation#1365]
The documentation for `npm ls` highlights that significant changes to the command might be comming with version 8. 

https://docs.npmjs.com/cli/commands/npm-ls
> A thorough re-examination of the use cases, intention, behavior, and output of this command, is currently underway. Expect significant changes to at least the default human-readable npm ls output in npm v8.

This is either obsolete or the version should be increased to the next one.

**Comment by rotu** [comment]
I think this is a generated file and has to be fixed upstream https://github.com/npm/documentation/commits/d3acafc1970fea9125dde7aacf85b7d4886e2ea9/content/cli/v10/commands/npm-ls.mdx

**Comment by wraithgar** [comment]
Yep! That file is sourced in the npm repo itself, so the fix would need to happen there.  It's ok for this issue to live in this repo though.

**Comment by rotu** [comment]
> Yep! That file is sourced in the npm repo itself, so the fix would need to happen there. It's ok for this issue to live in this repo though.

I don't care where this issue lives but it seems https://github.com/npm/cli/issues/6773 was closed in error by @milaninfy. Where's the best place to report this so it is most readily actionable?

**Comment by wraithgar** [comment]
Yeah that one was closed in error.  Either repo works.
