### ISSUE TITLE
Npm website sign up

### ISSUE THREAD

**Issue by yaxingson** [npm/documentation#1371]
I have deleted the original user name, why the page shows that this user name has been used when I re-register with the previous user name, I want to know how to solve this problem, please help me.

<img src="https://www.helloimg.com/i/2024/11/14/67356c770f012.png" />

**Comment by kenshanta** [comment]
Are you sure no one else took it already?
Whats the username?

**Comment by wraithgar** [comment]
This repo is for bugs in the docs site, for general support please reach out to https://www.npmjs.com/support
