### ISSUE TITLE
[website] the search doesn't find exact-match anymore for 'underdog' packages

### ISSUE THREAD

**Issue by teetotum** [npm/documentation#1408]
Sorry for putting this on https://github.com/npm/documentation but I couldn't find any other place to put this because:
- https://github.com/npm/www is archived
- the links I found there are dead:
  - "Requests for help, diagnostics and other support questions go in the [support category on npm.community](https://npm.community/c/support)."
  - "Reports of bugs go in the [bugs category](https://npm.community/c/bugs)."

The actual issue: I can't find some packages (that don't really have many downloads or users generally speaking - so they are rather underdog) via the search; but I would expect to find them as the first search hit when I typed in the exact package name at least.

I understand that packages with very few downloads or very new packages are deprioritized, but making them unfindable is clearly a bug.

I could not find the following packages via the search:
- `version-me`
- `simple-commitlint`
- `react-attached-properties`
- `url-search-params-delete`
- `mock-switch`
- `vite-plugin-unified`

but all of them exist:
- [version-me](https://www.npmjs.com/package/version-me)
- [simple-commitlint](https://www.npmjs.com/package/simple-commitlint)
- [react-attached-properties](https://www.npmjs.com/package/react-attached-properties)
- [url-search-params-delete](https://www.npmjs.com/package/url-search-params-delete)
- [mock-switch](https://www.npmjs.com/package/mock-switch)
- [vite-plugin-unified](https://www.npmjs.com/package/vite-plugin-unified)

It is especially frustrating for developers who haven't gathered a large user base for their packages yet, when you can't even find their packages with the exact package name.

**Comment by wraithgar** [comment]
This repo is for issues with the documentation site itself.  For website and registry issues please use https://www.npmjs.com/support
