### ISSUE TITLE
[BUG] copy button hiding text

### ISSUE THREAD

**Issue by sachinraja** [npm/documentation#19]
# What / Why
The text at the end of each code block is cut off by the copy button.
![image](https://user-images.githubusercontent.com/58836760/122847294-44823280-d2bc-11eb-9081-189517beb81f.png)
[image from here](https://docs.npmjs.com/cli/v7/using-npm/scripts#special-packagejson-config-object)

The full line is `http.createServer(...).listen(process.env.npm_package_config_port)`, but the reader can only see `http.createServer(...).listen(process.env.npm_package_config`.

## Where

* any block where the text fills the entire line

### Current Behavior

* copy button covers last part of line in code block

### Steps to Reproduce

* go to any block where the text fills the entire line on the documentation website

### Expected Behavior

* the copy button should not hide any text or should only show on hover (this is what GitHub does)

**Comment by MylesBorins** [comment]
hey @sachinraja thanks for reporting. It might take our team a couple weeks to find time to work on this. I'm throwing a `help wanted` label on here in the mean time in case anyone wants to try and fix this

**Comment by khairnarsaurabh23** [comment]
@MylesBorins i want to work on this issue?

**Comment by khairnarsaurabh23** [comment]
It will be greate if i'll get some resourses for reference?

**Comment by MylesBorins** [comment]
hey @khairnarsaurabh23 I just noticed that it appears @sachinraja might have fixed this in https://github.com/npm/doctornpm/pull/1 (and we totally missed it). Will give that a review this week and let you know if that closes this issue

**Comment by sanmins** [comment]
[BUG] copy button hiding text

**Comment by sanmins** [comment]
[BUG] copy button hiding text

**Comment by sanmins** [comment]
yy

**Comment by AshwanthramKL** [comment]
Hey this still open?
