### ISSUE TITLE
[BUG] Broken externally-linked URL https://docs.npmjs.com/files/package-locks

### ISSUE THREAD

**Issue by SamB** [npm/documentation#203]
# What / Why
The URL <https://docs.npmjs.com/files/package-locks>, linked to from other sites, 404s.

Looks like it used to redirect to <https://docs.npmjs.com/cli/v6/configuring-npm/package-locks>, as of <https://web.archive.org/web/20201214093528/https://docs.npmjs.com/files/package-locks>, but no longer did as of <https://web.archive.org/web/20211126181007/https://docs.npmjs.com/files/package-locks>.

And for some reason that topic is only available for 6.x?

P.S. This issue template seems entirely unhelpful for this documentation project.

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by lukekarrys** [comment]
That page was removed as part of v7 (https://github.com/npm/cli/pull/2475). I've updated the redirect to point to the v6 version for now.
