### ISSUE TITLE
[BUG] 404 error while publishing npm package

### ISSUE THREAD

**Issue by knev** [npm/documentation#209]
# What / Why

> Documentation isn't complete and can lead to a 404 error

## When

* using the `npm publish` command

## References

* The documentation should be updated to mention `npm login` before `npm publish` 
documentation/content/packages-and-modules/contributing-packages-to-the-registry/creating-and-publishing-private-packages.mdx

**Comment by MylesBorins** [comment]
please report any registry outages to https://npmjs.com/support

**Comment by PLG** [comment]
This is not about an outage, but about updating the documentation.
