### ISSUE TITLE
Explanation of "idealTree" and "reify"

### ISSUE THREAD

**Issue by ZakareyaAlatoli** [npm/documentation#211]
# What / Why

> When installing packages via npm the console will print a lines like
<code>idealTree:[package-name]</code>
and
<code>reify:[package-name]</code>
What do those terms mean? What is npm doing exactly?

**Comment by ljharb** [comment]
reify is putting stuff on disk; the ideal tree is the conceptually ideal dependency tree npm has constructed from package.json and a lockfile.

**Comment by wraithgar** [comment]
Those are debug messages that help us during support, they end up in the logfile.  Sometimes due to quirks in how the progress bar currently works in npm, they also end up briefly displayed on the console.
