### ISSUE TITLE
[BUG] Git logo link not working!!

### ISSUE THREAD

**Issue by restrictedCodex** [npm/documentation#26]
# What / Why
I was surfing through the npm website. There is a Github logo in the footer that doesn't link to the repo.

## When
whenever you open the website

## Where
npm official website : npmjs.com

### Current Behavior
inactive icon links

### Expected Behavior
should link to this organization repo

## Who
@everyone

## References
check out the website npmjs.com

**Comment by ljharb** [comment]
It’s not supposed to - it’s the company that owns npm.

**Comment by MylesBorins** [comment]
hey @restrictedCodex thanks for opening the issue. This repo is for tracking work on the docs, where as this is a report about the general website.

There is an existing discussion tracking the addition of the GitHub logo to the site

https://github.com/npm/feedback/discussions/93

We'll keep that discussion up to date with developments. Currently talking to engineering about what we want to do with those icons.
