### ISSUE TITLE
[BUG] Unclear unpublish policy

### ISSUE THREAD

**Issue by theonlypwner** [npm/documentation#29]
# What / Why
The document `unpublish.md` (at `content/policies/unpublish.mdx`) does not specify whether the conditions are joined by conjunction or disjunction. To reduce confusion, it should be clarified by adding a word such as `and` or `or` or adding a clause `you can unpublish a package that meets any of these conditions:` or `you can unpublish a package that meets all of these conditions:`. Also, it seems like `and` is intended, not `or`.

This is the original:

> ## Packages published more than 72 hours ago
> Regardless of how long ago a package was published, you can unpublish a package that:
> * no other packages in the npm Public Registry depend on
> * had less than 300 downloads over the last week
> * has a single owner/maintainer

These versions are more clear:

> ## Packages published more than 72 hours ago
> Regardless of how long ago a package was published, you can unpublish a package that:
> * no other packages in the npm Public Registry depend on,
> * had less than 300 downloads over the last week, and
> * has a single owner/maintainer

> ## Packages published more than 72 hours ago
> Regardless of how long ago a package was published, you can unpublish a package that meets all of these conditions:
> * no other packages in the npm Public Registry depend on
> * had less than 300 downloads over the last week
> * has a single owner/maintainer

(same as npm/policies#139)

## When, Where, How, Current Behavior,Steps to Reproduce, Expected Behavior, Who, References
* n/a

**Comment by ljharb** [comment]
Rather than adding a conjunction awkwardly into a bulleted list, perhaps “you can unpublish a package that meets all of these criteria:”?

**Comment by theonlypwner** [comment]
I suggested that as an alternative ("adding a clause"), but adding one conjunction is shorter.

Either change would fix the issue.

**Comment by MylesBorins** [comment]
We've updated the unpublish policy since this was opened... please reopen if policy is still unclear

**Comment by theonlypwner** [comment]
@MylesBorins The relevant part of the policy seems to have been unchanged. Please reopen this issue.

**Comment by MylesBorins** [comment]
I'm reopening, but I disagree that any action needs to be taken. I think it it is clear that all three of the items in the list need to be true in order to be able to unpublish.

**Comment by theonlypwner** [comment]
A small edit to make it clear that it's a conjunction rather than disjunction would resolve the issue.
