### ISSUE TITLE
[BUG] Link to field `description` on article `package.json` is broken

### ISSUE THREAD

**Issue by LinqLover** [npm/documentation#34]
# What / Why
![image](https://user-images.githubusercontent.com/38782922/132956153-7cbf2daa-8376-46a6-b703-7c3692d292a9.png)

## When
Scroll down to the section `description` (*not* `Description` above)

## Where
https://docs.npmjs.com/cli/v7/configuring-npm/package-json

## How
URLs don't care about casing so the HTML anchor is ambiguous. Interestingly, the ToC uses a better strategy for creating unique anchors but the HTML content itself does not adopt this strategy.

### Current Behavior
Cannot create a valid link to the field `description`

### Steps to Reproduce
Option 1: Click here
![image](https://user-images.githubusercontent.com/38782922/132956166-9c0f58f8-55de-48c9-935b-c484c9875815.png)
Option 2: Click on `description` here
![image](https://user-images.githubusercontent.com/38782922/132956185-adef512a-5ceb-4bcc-b35e-ec7bbb929f90.png)

### Expected Behavior
Option 1: Link is invalid
Option 2: Link refers to wrong section

**Comment by wraithgar** [comment]
This is a known problem with a proposed PR [here](https://github.com/npm/cli/pull/3653). Not sure if removing the original "description" is the solution here though.

**Comment by wraithgar** [comment]
The proposed solution was not the right one, this is something that is going to need to be fixed in the docs site itself. It *should* be able to handle this (in fact the t.o.c appears to already try)

**Comment by MylesBorins** [comment]
@wraithgar what are you imagining the next steps here are"?

**Comment by wraithgar** [comment]
@MylesBorins I have no idea where to start. There seems to be a bug with whatever markdown rendering library is being used when there are headers w/ duplicate names.  The table of contents does it correctly, but the page itself does not.

**Comment by wraithgar** [comment]
Github's markdown renderer also does not have this bug https://github.com/npm/cli/blob/latest/docs/content/configuring-npm/package-json.md#description-1

**Comment by Satoshi-MM** [comment]
Close
