### ISSUE TITLE
[BUG] using unknown tool in documentation

### ISSUE THREAD

**Issue by msangel** [npm/documentation#45]
# What / Why
The page: https://github.com/npm/documentation/blob/main/content/packages-and-modules/securing-your-code/verifying-the-pgp-signature-for-a-package-from-the-npm-public-registry.mdx (also [this](https://docs.npmjs.com/verifying-the-pgp-signature-for-a-package-from-the-npm-public-registry)) contains example code and its impossible to execute that as it refers to an unknown command-line utility. The code:
```bash
http GET https://registry.npmjs.org/light-cycle | json "versions['1.4.3'].dist.npm-signature" > sig-to-check
```
The error: `Command 'json' not found`. Shouldn't be here [jq](https://stedolan.github.io/jq/)? Or if there really exist some `json` cmd, please instruct on how to install it in the `Prerequisites` section of the same article.
Also `http`:  `Command 'http' not found`. Assuming `curl`. Also add to `Prerequisites`. 
> n/a

## When
execute: `json` shell or `http` shell

## Where
bash(ubuntu).

## How
typing command by keyboard

### Current Behavior
* n/a

### Steps to Reproduce
run this on any computer that doesn't have any `json` and `http` packages

### Expected Behavior
jq? curl?

## Who
linux user

## References
* n/a

**Comment by lukekarrys** [comment]
Thanks for the issue @msangel! I think we should have as few prerequisites as possible so I suggest we move all the `json` examples to `npx json` and `http` to `npm view --json`.

For example, here's an `npm` only example for that same command:

```
npm view light-cycle@1.4.3 --json | npm exec json ".dist.npm-signature"
```
