### ISSUE TITLE
[BUG] NPM 8.1 is not present in the documentation despite being the default NPM version distributed in the Node LTS version

### ISSUE THREAD

**Issue by wandyezj** [npm/documentation#47]
# What / Why

> NPM 8.1 is the default version of NPM distributed with Node LTS, yet there is no documentation for NPM 8.1, shouldn't NPM 8.1 be the current release?

## When

* n/a

## Where

* n/a

### Current Behavior

* n/a

### Steps to Reproduce

* n/a

### Expected Behavior

* n/a

## Who

* n/a

## References

* n/a

**Comment by wraithgar** [comment]
npm 8 is now on the docs site
