### ISSUE TITLE
Don't autofocus the npm version dropdown

### ISSUE THREAD

**Issue by sersorrel** [npm/documentation#483]
The npm version dropdown:

![image](https://user-images.githubusercontent.com/9433472/225316679-7a320f4c-9bce-4f64-9e54-6fa60196bc52.png)

is focused when the page loads:

https://github.com/npm/documentation/blob/f8069dd5343aafd12550259f6c6ead0234141473/theme/src/components/variant-select.js#L66

This is user-hostile and prevents scrolling with spacebar when the page loads. If the intent was to make it easy to change the selected npm version with the keyboard (which seems a bizarre choice, frankly, I'm not sure I ever remember doing that, and other popular projects (e.g. the Python documentation) don't autofocus their version selector elements), it's misguided – whilst pressing space opens the dropdown, it's not then possible to navigate the dropdown with standard keyboard controls like the arrow keys (or, as far as I can tell, with any keyboard controls at all: pressing tab just moves focus to the ToC).

This was added in 4505fceab910de6aa3cb1346e05d229f564efcea, as part of #303.

**Comment by damacadmin** [comment]
Thanks for all the hard work and patience on seeing this through!
