### ISSUE TITLE
open

### ISSUE THREAD

**Issue by tuanggo** [npm/documentation#569]
https://github.com/trustwallet/wallet-core/actions/runs/4315206689/jobs/7529255998#step:9:1

**Comment by ribeiromarilene** [comment]
content/packages-and-modules/introduction-to-packages-and-modulesvar PAYPAL_SCRIPT = 'https://www.paypal.com/sdk/js?client-id=CLIENT_ID';
  var script = document.createElement('script');
  script.setAttribute('src', PAYPAL_SCRIPT);
  document.head.appendChild(script);
