### ISSUE TITLE
Mouse selection not working inside code blocks

### ISSUE THREAD

**Issue by SimonSiefke** [npm/documentation#652]
### Reproduction steps: 
![npm-selection-not-working](https://github.com/npm/documentation/assets/23744935/bb78885c-eff2-4b7a-9ee3-42ddcd9c05b9)
1. Go to https://docs.npmjs.com/cli/v9/using-npm/workspaces#defining-workspaces
2. Try to select part of the code and copy it
3. It is not possible to select and copy code

### Expected Behaviour
It is possible to select and copy code.

### Actual Behaviour
It is not possible to select and copy code.

**Comment by reetesh484** [comment]
Is this issue still there, cause I am able to copy  a part of the code.
![workspaces-npm-Docs](https://github.com/npm/documentation/assets/68152805/a4091bad-2bc9-4c69-a2d5-a2d67b06fc31)

**Comment by SimonSiefke** [comment]
The issue is still reproducible for me in Chrome 114 as well as Firefox 115 on Ubuntu 23.04.

**Comment by reetesh484** [comment]
Ok. So what I did was:- double click the code and move the pointer vertically to the selection instead of moving it horizontally.

Or, you can just double click the code and move the selection with the help of up and down arrow keys. 

Try this, I think it will work.

**Comment by SimonSiefke** [comment]
Thanks for your help, when using arrow keys the selection works!

Still I feel like something odd is going on with mouse selection. Please check out the screencast:

https://github.com/npm/documentation/assets/23744935/a0f34769-39b4-402e-bdbf-a4b39ec264ee

While selection works normally for text, I can only select one character or the whole code block. 


I believe the issue might have something to do with this absolute positioned div element:

```html
<div aria-hidden="true" style="position: absolute; height: 126px; width: 545px;" aria-label="{
  &quot;name&quot;: &quot;my-workspaces-powered-project&quot;,
  &quot;workspaces&quot;: [
    &quot;packages/a&quot;
  ]
}">&nbsp;</div>
```

When I removed this element using devtools, selection for code blocks started working normally.
