### ISSUE TITLE
[QUESTION] Delete organization by mistake

### ISSUE THREAD

**Issue by mqyun** [npm/documentation#66]
# What / Why

Hello, I have a problem now. Add an organization and move the package to this organization, then accidentally delete the organization, and then the package is gone. Is there any way to recover?
> n/a

## Where

* n/a

## Who

* n/a

## References

* n/a

**Comment by wraithgar** [comment]
This is an npm registry question and you'll need to go through [support](https://www.npmjs.com/support)
