### ISSUE TITLE
Documentation about package-locks

### ISSUE THREAD

**Issue by bigfatbird** [npm/documentation#721]
Hi, I was just wondering why this site https://docs.npmjs.com/cli/v6/configuring-npm/package-locks is deprecated or redirects for newer versions of npm.

I was working around package-lock version conflicts and found out that https://www.npmjs.com/package/npm-merge-driver is also archived without any documentation of it being deprecated or not, so i was wondering if there are better approaches to this. 

Best regards

**Comment by wraithgar** [comment]
npm automatically resolves conflicts in the package-lock internally now with https://github.com/npm/parse-conflict-json#readme


cf https://github.com/npm/cli/blob/68031f2ae1cd5d49b0fb263da1a7eae62712ff97/workspaces/arborist/lib/shrinkwrap.js#L52

**Comment by wraithgar** [comment]
That page was removed as part of the v7 updates https://github.com/npm/cli/pull/2475

Because there were other sites that linked to it, it was redirected to the v6 version so that it wouldn't 404 https://github.com/npm/documentation/issues/203

**Comment by bigfatbird** [comment]
Oh I'm wondering because we had many merge conflicts when upgrading packages from branches and merging them into main.

Maybe I'm using something wrong then. Thank you
