### ISSUE TITLE
I created an NPM package. Why are the headings displaying in red?

### ISSUE THREAD

**Issue by Kajanan02** [npm/documentation#729]
![Screenshot from 2023-10-06 01-27-19](https://github.com/npm/documentation/assets/64707660/7dd51e01-2cdb-4afb-b41f-e7d682617235)

Readme code

## react-native-send-direct-sms

React Native Send SMS is a JavaScript library for React Native applications that provides a convenient way to send SMS messages programmatically. It enables developers to integrate SMS functionality into their mobile apps, allowing them to send text messages to specified recipients directly from the app. This can be useful for implementing features like SMS-based authentication, notifications, or any other communication that requires sending SMS messages.

## Installation

```
npm install react-native-send-direct-sms
```

## Android Setup

It's crucial to ask for permission in your AndroidManifest.xml file if you need to use Send Message directly.

Please add this line to your AndroidManifest.xml before using this example:
- In `android/app/src/main/AndroidManifest.xml` add the following lines:

```xml
<uses-permission android:name="android.permission.SEND_SMS"/>
```

## Usage

```js
import { SendDirectSms } from 'react-native-send-direct-sms';
// ...

function sendSmsData(mobileNumber, bodySMS) {
  SendDirectSms(mobileNumber, bodySMS)
    .then((res) => console.log("then", res))
    .catch((err) => console.log("catch", err))
}

```

## Example

<img src="https://github.com/Kajanan02/resources/blob/main/images/sendsmsexample.jpg" alt="Example Image" width="50%">

```
import * as React from 'react';

import { StyleSheet, View, Text, TextInput, TouchableOpacity } from 'react-native';
import { SendDirectSms } from 'react-native-send-direct-sms';

export default function App() {
  const [mobileNumber, setMobileNumber] = React.useState('');
  const [bodySMS, setBodySMS] = React.useState('Hello World');


  function sendSmsData(mobileNumber: string, bodySMS: string) {
    SendDirectSms(mobileNumber, bodySMS)
      .then((res: any) => console.log('then', res))
      .catch((err: any) => console.log('catch', err));
  }

  return (
    <View style={styles.container}>
      {/*<Text>Result: {result}</Text>*/}
      <Text style={styles.titleTextsmall}>
        Enter Recipients Number
      </Text>
      <TextInput
        value={mobileNumber}
        onChangeText={
          (mobileNumber) => setMobileNumber(mobileNumber)
        }
        placeholder={'Enter Mobile Number'}
        keyboardType='numeric'
        style={styles.textInput}
      />
      <Text style={styles.titleTextsmall}>
        Enter SMS Body
      </Text>
      <TextInput
        value={bodySMS}
        onChangeText={(bodySMS) => setBodySMS(bodySMS)}
        placeholder={'Enter SMS body'}
        style={styles.textInput}
      />
      <TouchableOpacity style={styles.sendButton} onPress={() => sendSmsData(mobileNumber, bodySMS)}>
        <Text style={styles.sendButtonLabel}>Send SMS</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  box: {
    width: 60,
    height: 60,
    marginVertical: 20,
  },
  sendButtonLabel: {
    fontSize: 16,
    color: '#FFFFFF',

  },
  sendButton: {
    width: '100%',
    backgroundColor: '#22C674',
    borderRadius: 4,
    opacity: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    marginTop: 30,
  },
  titleTextsmall: {
    marginBottom: 8,
    marginTop: 16,
    fontSize: 16,
    alignSelf: 'flex-start',
  },
  textInput: {
    paddingLeft: 16,
    fontSize: 14,
    borderWidth: 1,
    borderColor: '#3F44511F',
    borderRadius: 4,
    height: 44,
    color: '#000000',
    opacity: 0.75,
    width: '100%',
  },
});


```

## Contributing

See the [contributing guide](CONTRIBUTING.md) to learn how to contribute to the repository and the development workflow.

Or open up [an issue](https://github.com/Kajanan02/react-native-send-sms/issues).

---
## Discussion and Collaboration

In addition to the [GitHub Issues](https://github.com/Kajanan02/react-native-send-sms/issues) page.

## License

MIT

---

Made with [create-react-native-library](https://github.com/callstack/react-native-builder-bob)

**Comment by wraithgar** [comment]
![Screenshot 2023-10-05 at 2 06 17 PM](https://github.com/npm/documentation/assets/36607/fcc9af0b-93e0-4f2a-8738-88b1f26c95d8)

I'm not seeing that.

**Comment by Kajanan02** [comment]
@wraithgar only my package show like that why my [package link](https://www.npmjs.com/package/react-native-send-direct-sms)

**Comment by ljharb** [comment]
I see it too; the first line of your readme should have one #, not two, but otherwise maybe it’s that your image on the first line is missing square brackets around the ! part?

**Comment by wraithgar** [comment]
This is something happening only "new" readmes (i.e. readmes being rendered recently) and it is being looked into.

**Comment by lukekarrys** [comment]
This is due to a change in the README html structure from some API changes. I am working on a fix now. I'm going to close this issue since it is not an issue on the documentation site, but I will be updating https://github.com/npm/feedback/discussions/1010 when it is fixed.

**Comment by Kajanan02** [comment]
@ljharb I started one #, but It's not appearing then I changed two# and I think in my case we don't want square brackets in image's first line

**Comment by Kajanan02** [comment]
@wraithgar @lukekarrys Thank you for the update
