### ISSUE TITLE
npm update not working in my project

### ISSUE THREAD

**Issue by unrealhenry** [npm/documentation#856]
<img width="1908" alt="Screenshot 2023-12-04 at 23 02 42" src="https://github.com/npm/documentation/assets/92013160/15b6cbab-27b7-462e-b293-5dd002d222a0">

I need help!! Thanks for all!

**Comment by ljharb** [comment]
You have to explicitly update to something that’s a major bump / a breaking change, npm update won’t do that for you.

**Comment by wraithgar** [comment]
https://docs.npmjs.com/cli/v10/commands/npm-update#description

> Note that by default npm update will not update the semver values of direct dependencies in your project package.json, if you want to also update values in package.json you can run: npm update --save (or add the save=true option to a [configuration file](https://docs.npmjs.com/cli/v10/configuring-npm/npmrc) to make that the default behavior).
