### ISSUE TITLE
`dependencies` and `devDependencies` documents for application projects

### ISSUE THREAD

**Issue by jiro4989** [npm/documentation#862]
Hello.

Additional description required for [dependencies](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#dependencies) or [devDependencies](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#devdependencies).

> Please do not put test harnesses or transpilers or other "development" time tools in your dependencies object. See devDependencies, below.

This description is correct for library projects.
But, I think it's different for application projects.
For web applications written in TypeScript, `typescript` (transpilers) is required to run in production environment.
In this case, `typescript` is a transpiler, but it is a package required for `dependencies`.

So, I think it is necessary to write "`dependencies` and `devDependencies` for library projects" and "`dependencies` and `devDependencies` for application projects" in the description.

**Comment by ljharb** [comment]
npm ci isn’t for deployment; you should be tarring up a pruned node_modules and deploying that. Don’t ever npm install in production. So, you shouldn’t ever be omitting dev deps - there’s no use case for it.

**Comment by jiro4989** [comment]
So build process needs typescript compiler, webpack etc. Test process needs Jest, Eslint and prettier etc. But these do not need for build process.

I was thinking that `devDependencies` could be used to exclude packages that are only needed in the testing process. Is this the wrong usage?

**Comment by ljharb** [comment]
Yes, that's the wrong usage. Some have asked for more granular categories like "test deps" and "build deps" - but all of these are basically always _dev_ deps.

`dependencies` is the place where everything that's conceptually needed *at runtime* goes, and `devDependencies` is where everything else goes, whether an application or a package.

**Comment by jiro4989** [comment]
OK, Thanks a lot.
I solved my all questions.
Thank you for your help 👍
