### ISSUE TITLE
attempt to update npm totally broke it 

### ISSUE THREAD

**Issue by cur4so** [npm/documentation#879]
any way to return to the previous version?
```
ERROR: npm v10.2.5 is known not to run on Node.js v12.22.8.  This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.

ERROR:
/usr/lib/node_modules/npm/lib/utils/exit-handler.js:19
  const hasLoadedNpm = npm?.config.loaded
                           ^

SyntaxError: Unexpected token '.
....
```
node versions  `^18.17.0 || >=20.5.0` are incompatible with my system

**Comment by wraithgar** [comment]
There is a script at `https://www.npmjs.com/install.sh` that can be used to bootstrap npm on a system that doesn't have a working version of npm.

You can set the `$npm_install` shell variable to the specific version you want and then run the script.

**Comment by cur4so** [comment]
thanks, wraithgar, for your response. It did resolved the issue (with some extra debugging and searching). But the issue itself is still there and the next person on an outdated system, trying to update npm will likely ends up at the same point. 
Don't you think adding compatibility check in the update process will be useful? If node or other dependencies are incompatible with the version of npm being installed - exit with the found incompatibility message instead of breaking existing npm. It'd save a lot of time for people who are focused on other tasks.

**Comment by wraithgar** [comment]
Newer versions of npm do have this fix.  This obviously does no good for folks on a version of npm before the fix, but as time goes on we'll see less of this.

If you were to install npm 8.19.4 (the newest version that runs in node 12) you would get this:

```sh
~ $ npm -v
8.19.4
~ $ node --version
v12.22.12
~ $ npm i -g npm@latest
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@10.2.5
npm ERR! notsup Not compatible with your version of node/npm: npm@10.2.5
npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v12.22.12"}
````
