### ISSUE TITLE
Signup on npmjs.com is not working !

### ISSUE THREAD

**Issue by duelingbenjos** [npm/documentation#976]
When going through the signup flow on npmjs.com, upon submission of the OTP, the next page is a 404, making it impossible to sign up.

**Comment by realalex** [comment]
+1

They've also implemented these idiotic puzzles that took me 10 minutes to solve, then I had to start over because I got one wrong.
![Screenshot 2024-02-18 at 3 05 24 PM](https://github.com/npm/documentation/assets/1354110/a5ed3c81-7cde-451f-91a5-64d7af766493)

**Comment by ldunnplaymint** [comment]
I have hit this issue too. If I try to reset password, the email never comes through and attempting to sign up again gives me an "Account already created" message.

**Comment by wraithgar** [comment]
If you are having trouble w/ the npmjs website please contact support at https://www.npmjs.com/support, this repo is for the documentation site itself, and support doesn't follow the issues here.
